image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install pip requirements
    init: pip install -r requirements.txt
    command: 'echo "pip install -r requirements.txt"'
  - name: Install pre-commit hooks
    command: >
      pre-commit install --install-hooks
      && printf "\n \n \n Please close this window
