# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image:
  file: Dockerfile

# Command to start on workspace startup (optional)
tasks:
  - name: Prepare workspace
    # pip install -r requirements is in Dockerfile
    command: >
      export PIP_USER=false
      && pre-commit install --install-hooks

# Ports to expose on workspace startup (optional)
ports:
  # Grip server
  - port: 6419
    onOpen: open-preview

# Github prebuilds
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
