#------------------------------------------------------------------------------#
name: CI
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/ci.yaml*'
      - 'advent_of_code_2020/*.py'
      - 'input/*.txt'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]

#------------------------------------------------------------------------------#
jobs:
  #----------------------------------------------------------------------------#
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    #--------------------------------------------------------------------------#
    steps:
      #------------------------------------------------------------------------#
      # Checkout Repo
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Python setup ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      #------------------------------------------------------------------------#
      # Test
      - name: Run script
        run: advent_of_code_2020/advent_of_code_2020.py
      #------------------------------------------------------------------------#
      # Artifacts
