#------------------------------------------------------------------------------#
name: CI
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/ci.yaml*'
      - 'advent_of_code_2020/*.py'
      - 'input/*.txt'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]

#------------------------------------------------------------------------------#
jobs:
  #----------------------------------------------------------------------------#
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    #--------------------------------------------------------------------------#
    steps:
      #------------------------------------------------------------------------#
      # Install dependencies
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Python setup ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Package install
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      #------------------------------------------------------------------------#
      # CI
      - name: Test
        run: python -m coverage run -m pytest --cov=advent_of_code_2020 --cov-report=xml test/test_advent.py
       #------------------------------------------------------------------------#
      # Test
      - name: Run script
        run: advent_of_code_2020/advent_of_code_2020.py
      #------------------------------------------------------------------------#
      # Upload codecov report
      - name: Codecov Upload
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
      #------------------------------------------------------------------------#
      # Artifacts
